#!/usr/bin/env Rscript
# 10_figures.R — Publication figures (AGG Original Article)
# Study 17: IC-Environment Fit and Disability-Free Survival
# v3.1 — Add standardized 5-year absolute risks to Figure 2
#
# Main-text figures:
#   Fig 1: STROBE flowchart (generated by 11_strobe_flowchart.R)
#   Fig 2: Panel A: Forest plot + Panel B: Marginal effect + Panel C: 5-year risk
#   Fig 3: Panel A: KM 4-group DFS + risk table + Panel B: MSM stratified dot plot
#   Table 1: Baseline characteristics (separate file)
#   Fig 3C: Sensitivity analysis forest plot (21 estimates, domain-grouped)
#
# Supplementary figures:
#   eFig 1: LCGA trajectory classes
#   eFig 2: IPTW weight diagnostics
#   eFig 3: Marginal effect plot (standalone high-res, for appendix)
#
# Inputs:  results/*.csv, data/*.rds
# Outputs: figures/*.pdf, figures/*.tiff

library(tidyverse)
library(survival)
library(metafor)
library(patchwork)

set.seed(2024)
t0 <- Sys.time()

dir.create("figures", showWarnings = FALSE)

# ==============================================================================
# GLOBAL: Publication theme and colour palette
# ==============================================================================

# Use a local system font so PDF rendering does not depend on network access.
base_family <- "Arial"
cat("  Using system Arial font\n")

lancet_colors <- c(
  blue = "#00468B", red = "#AD002A", green = "#42B540",
  purple = "#925E9F", orange = "#ED7D31", grey = "#7F7F7F",
  ltblue = "#0099B4", ltgrey = "#ADB6B6"
)

theme_lancet <- theme_minimal(base_size = 10, base_family = base_family) +
  theme(
    plot.title       = element_blank(),
    plot.subtitle    = element_blank(),
    axis.line.x      = element_line(color = "grey30", linewidth = 0.4),
    axis.line.y      = element_line(color = "grey30", linewidth = 0.4),
    axis.ticks       = element_line(color = "grey30", linewidth = 0.3),
    axis.text        = element_text(size = 8, color = "grey20"),
    axis.title       = element_text(size = 9, color = "grey10"),
    panel.grid.major = element_line(color = "grey92", linewidth = 0.3),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border     = element_blank(),
    strip.background = element_rect(fill = "grey96", color = NA),
    strip.text       = element_text(face = "bold", size = 9),
    legend.position  = "bottom",
    legend.title     = element_text(size = 8, face = "bold"),
    legend.text      = element_text(size = 8),
    legend.key.size  = unit(0.4, "cm"),
    legend.background = element_blank(),
    plot.margin      = margin(10, 15, 10, 10)
  )

fig_width_2col <- 7.2
fig_dpi <- 300

# ==============================================================================
cat("=== FIGURE 2: Forest + Marginal Effect + Standardized 5-year Risk ===\n")
# ==============================================================================

# --- Panel A: Forest Plot ---
stage1 <- read_csv("results/stage1_estimates.csv", show_col_types = FALSE)
stage2 <- read_csv("results/stage2_pooled.csv", show_col_types = FALSE)

build_forest_block <- function(s1, s2, term_label) {
  cohort_rows <- s1 %>%
    transmute(
      term = term_label, label = cohort, type = "cohort",
      hr, ci_lo = hr_lower, ci_hi = hr_upper,
      hr_text = sprintf("%.2f (%.2f\u2013%.2f)", hr, hr_lower, hr_upper)
    )
  pooled_row <- s2 %>% slice(1) %>%
    transmute(
      term = term_label, label = "Pooled (RE)", type = "pooled",
      hr = pooled_hr, ci_lo = hr_lower, ci_hi = hr_upper,
      hr_text = sprintf(
        "%.2f (%.2f\u2013%.2f)\nI\u00b2 %.1f%%",
        pooled_hr, hr_lower, hr_upper, I2
      )
    )
  bind_rows(cohort_rows, pooled_row)
}

s1_ic  <- stage1 %>% filter(variable == "ic_cfa" & model == "M3_Both")
s2_ic  <- stage2 %>% filter(variable == "ic_cfa" & model == "M3_Both")
s1_env <- stage1 %>% filter(variable == "env_formative" & model == "M3_Both")
s2_env <- stage2 %>% filter(variable == "env_formative" & model == "M3_Both")
s1_int <- stage1 %>% filter(variable == "ic_env_cont" & model == "M4_Interaction")
s2_int <- stage2 %>% filter(variable == "ic_env_cont" & model == "M4_Interaction")

forest_data <- bind_rows(
  build_forest_block(s1_ic, s2_ic, "Intrinsic Capacity"),
  build_forest_block(s1_env, s2_env, "Environment Support"),
  build_forest_block(s1_int, s2_int, "IC \u00d7 Environment")
)

cohort_order <- c("CHARLS", "ELSA", "HRS", "MHAS", "SHARE", "Pooled (RE)")
forest_data$label <- factor(forest_data$label, levels = rev(cohort_order))
forest_data$term  <- factor(forest_data$term,
  levels = c("Intrinsic Capacity", "Environment Support", "IC \u00d7 Environment"))

pA <- ggplot(forest_data, aes(x = hr, y = label)) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey60", linewidth = 0.4) +
  geom_rect(
    data = forest_data %>% filter(type == "pooled") %>% distinct(term),
    aes(xmin = -Inf, xmax = Inf, ymin = 0.5, ymax = 1.5),
    inherit.aes = FALSE, fill = "grey96"
  ) +
  geom_point(data = . %>% filter(type == "cohort"),
             shape = 15, size = 2, color = "grey30") +
  geom_errorbarh(data = . %>% filter(type == "cohort"),
                 aes(xmin = ci_lo, xmax = ci_hi),
                 height = 0, linewidth = 0.5, color = "grey30") +
  geom_point(data = . %>% filter(type == "pooled"),
             shape = 18, size = 3.5, color = lancet_colors["red"]) +
  geom_errorbarh(data = . %>% filter(type == "pooled"),
                 aes(xmin = ci_lo, xmax = ci_hi),
                 height = 0, linewidth = 0.7, color = lancet_colors["red"]) +
  geom_text(aes(x = Inf, label = hr_text), hjust = -0.05, size = 2.2,
            family = base_family) +
  facet_wrap(~ term, ncol = 1, scales = "free_x") +
  coord_cartesian(clip = "off") +
  labs(x = "Hazard Ratio (95% CI)", y = NULL) +
  theme_lancet +
  theme(
    strip.text    = element_text(size = 8, face = "bold", hjust = 0),
    panel.spacing = unit(0.6, "cm"),
    plot.margin   = margin(5, 55, 5, 5)
  )

# --- Panel B: Marginal Effect Plot ---
# Recompute from survival_cohort (same method as 16_marginal_effect_plot.R)
surv_base <- readRDS("data/survival_cohort.rds")
cohorts <- unique(surv_base$cohort)

cohort_results <- list()
for (coh in cohorts) {
  dat <- surv_base %>%
    filter(cohort == coh & !is.na(ic_cfa_c) & !is.na(env_form_c) &
           !is.na(ic_env_cont) & time_dfs > 0)
  if (nrow(dat) < 100) next
  fit <- coxph(Surv(time_dfs, event_dfs) ~ ic_cfa_c + env_form_c +
               ic_env_cont + age + female + chronic_n, data = dat)
  coefs <- coef(fit); vc <- vcov(fit)
  idx_env <- which(names(coefs) == "env_form_c")
  idx_int <- which(names(coefs) == "ic_env_cont")
  cohort_results[[coh]] <- list(
    cohort = coh, n = nrow(dat),
    beta_env = coefs[idx_env], beta_int = coefs[idx_int],
    var_env = vc[idx_env, idx_env], var_int = vc[idx_int, idx_int],
    cov_ei = vc[idx_env, idx_int]
  )
}

cr <- bind_rows(lapply(cohort_results, function(x) {
  tibble(cohort = x$cohort, beta_env = x$beta_env, se_env = sqrt(x$var_env),
         beta_int = x$beta_int, se_int = sqrt(x$var_int), cov_ei = x$cov_ei)
}))

pool_env <- rma(yi = cr$beta_env, sei = cr$se_env, method = "REML")
pool_int <- rma(yi = cr$beta_int, sei = cr$se_int, method = "REML")
w <- 1 / (cr$se_env^2 + pool_env$tau2)
pooled_cov_ei <- sum(w * cr$cov_ei) / sum(w)

ic_grid <- seq(-2, 2, by = 0.05)

pooled_marg <- tibble(
  ic = ic_grid,
  log_hr = as.numeric(pool_env$beta) + as.numeric(pool_int$beta) * ic_grid,
  se = sqrt(as.numeric(pool_env$se)^2 +
            ic_grid^2 * as.numeric(pool_int$se)^2 +
            2 * ic_grid * pooled_cov_ei),
  hr = exp(log_hr), hr_lo = exp(log_hr - 1.96 * se), hr_hi = exp(log_hr + 1.96 * se),
  source = "Pooled (RE)"
)

cohort_marg <- bind_rows(lapply(cohort_results, function(x) {
  tibble(
    ic = ic_grid,
    log_hr = x$beta_env + x$beta_int * ic_grid,
    se = sqrt(x$var_env + ic_grid^2 * x$var_int + 2 * ic_grid * x$cov_ei),
    hr = exp(log_hr), hr_lo = exp(log_hr - 1.96 * se), hr_hi = exp(log_hr + 1.96 * se),
    source = x$cohort
  )
}))

cohort_colors <- c(
  "CHARLS" = "#7FABD3", "ELSA" = "#B8D4A0", "HRS" = "#E8B88A",
  "MHAS" = "#D4A5C9", "SHARE" = "#A8C8C8"
)

ic_dist <- surv_base %>% filter(!is.na(ic_cfa_c)) %>% pull(ic_cfa_c)
ic_dens <- tibble(ic = ic_dist) %>% filter(ic >= -2 & ic <= 2)

# Marginal effect main panel
pB_main <- ggplot() +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey60", linewidth = 0.4) +
  geom_line(data = cohort_marg,
            aes(x = ic, y = hr, color = source), linewidth = 0.35, alpha = 0.45) +
  geom_ribbon(data = pooled_marg,
              aes(x = ic, ymin = hr_lo, ymax = hr_hi),
              fill = lancet_colors["blue"], alpha = 0.15) +
  geom_line(data = pooled_marg,
            aes(x = ic, y = hr), color = lancet_colors["blue"], linewidth = 0.9) +
  geom_point(data = pooled_marg %>% filter(ic %in% c(-1, 0, 1)),
             aes(x = ic, y = hr),
             shape = 21, size = 2.2, fill = lancet_colors["blue"],
             color = "white", stroke = 0.7) +
  geom_text(data = pooled_marg %>% filter(ic %in% c(-1, 0, 1)) %>%
              mutate(label = sprintf("%.2f", hr)),
            aes(x = ic, y = hr, label = label),
            vjust = -1.3, size = 2.5, family = base_family,
            color = lancet_colors["blue"]) +
  scale_color_manual(values = cohort_colors, name = "Cohort") +
  scale_x_continuous(breaks = seq(-2, 2, 1),
                     labels = c("-2", "-1", "Mean", "+1", "+2")) +
  scale_y_continuous(breaks = seq(0.6, 1.1, 0.1)) +
  coord_cartesian(ylim = c(0.58, 1.12), xlim = c(-2, 2)) +
  labs(x = "Intrinsic capacity (SD from cohort mean)",
       y = "HR per 1-SD increase\nin environment support") +
  theme_lancet +
  theme(
    legend.position = c(0.82, 0.85),
    legend.background = element_rect(fill = alpha("white", 0.9), color = NA),
    legend.key.size = unit(0.25, "cm"),
    legend.text = element_text(size = 6), legend.title = element_text(size = 6.5)
  )

# IC density sub-panel
pB_dens <- ggplot(ic_dens, aes(x = ic)) +
  geom_histogram(aes(y = after_stat(density)), bins = 50,
                 fill = lancet_colors["ltgrey"], color = NA) +
  scale_x_continuous(breaks = seq(-2, 2, 1), limits = c(-2, 2), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = NULL, y = "Density") +
  theme_lancet +
  theme(
    axis.text.x = element_blank(), axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.y = element_text(size = 6), axis.text.y = element_text(size = 5.5),
    plot.margin = margin(0, 15, 0, 10)
  )

pB <- pB_main / pB_dens + plot_layout(heights = c(5, 1))

# --- Panel C: Standardized 5-year absolute DFS event risk ---
standardized_risk <- read_csv(
  "results/standardized_5y_risk_pooled.csv",
  show_col_types = FALSE
)

risk_plot_data <- bind_rows(
  standardized_risk %>% transmute(
    ic_stratum,
    environment = "Lower support (P25)",
    risk = pooled_risk_low_env,
    ci_lower = risk_low_env_ci_lower,
    ci_upper = risk_low_env_ci_upper
  ),
  standardized_risk %>% transmute(
    ic_stratum,
    environment = "Higher support (P75)",
    risk = pooled_risk_high_env,
    ci_lower = risk_high_env_ci_lower,
    ci_upper = risk_high_env_ci_upper
  )
) %>%
  mutate(
    ic_stratum = factor(ic_stratum, levels = c("Low", "Medium", "High")),
    environment = factor(
      environment,
      levels = c("Lower support (P25)", "Higher support (P75)")
    )
  )

rd_labels <- standardized_risk %>%
  mutate(
    ic_stratum = factor(ic_stratum, levels = c("Low", "Medium", "High")),
    label = sprintf(
      "RD %.1f pp\n%s %.1f\u2013%.1f",
      100 * pooled_risk_difference,
      "95% CI",
      100 * ci_lower,
      100 * ci_upper
    ),
    y = pmax(risk_low_env_ci_upper, risk_high_env_ci_upper) + 0.015
  )

pC <- ggplot(
  risk_plot_data,
  aes(x = ic_stratum, y = risk, color = environment, group = environment)
) +
  geom_line(linewidth = 0.7, position = position_dodge(width = 0.15)) +
  geom_errorbar(
    aes(ymin = ci_lower, ymax = ci_upper),
    width = 0.08, linewidth = 0.55,
    position = position_dodge(width = 0.15)
  ) +
  geom_point(size = 2.5, position = position_dodge(width = 0.15)) +
  geom_text(
    data = rd_labels,
    aes(x = ic_stratum, y = y, label = label),
    inherit.aes = FALSE, size = 2.25, lineheight = 0.95, color = "grey20",
    family = base_family
  ) +
  scale_color_manual(
    values = c(
      "Lower support (P25)" = "#D55E00",
      "Higher support (P75)" = "#0072B2"
    ),
    name = NULL
  ) +
  scale_y_continuous(
    labels = scales::label_percent(accuracy = 1),
    expand = expansion(mult = c(0.02, 0.14))
  ) +
  labs(
    x = "Intrinsic capacity tertile",
    y = "Standardized 5-year DFS event risk"
  ) +
  theme_lancet +
  theme(
    panel.grid.major.x = element_blank(),
    legend.position = "bottom",
    legend.text = element_text(size = 7),
    plot.margin = margin(5, 10, 5, 5)
  )

# --- Combine Figure 2: Panels A-C ---
# wrap_elements prevents patchwork from tagging internal sub-panels
fig2 <- (
  wrap_elements(full = pA) |
    wrap_elements(full = pB) |
    wrap_elements(full = pC)
) +
  plot_layout(widths = c(1.15, 1.1, 0.95)) +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(size = 12, face = "bold", family = base_family))

ggsave("figures/fig2_forest_marginal.pdf", fig2,
       width = fig_width_2col * 2, height = 9.5, device = cairo_pdf)
ggsave("figures/fig2_forest_marginal.tiff", fig2,
       width = fig_width_2col * 2, height = 9.5, dpi = fig_dpi, compression = "lzw")
cat("  Saved fig2_forest_marginal.pdf/tiff\n")

# ==============================================================================
cat("\n=== FIGURE 3: Panel A (KM + risk table) + Panel B (MSM stratified) ===\n")
# ==============================================================================

# --- Panel A: KM curves + number at risk ---
surv_km <- surv_base %>%
  filter(!is.na(ic_cat) & !is.na(env_cat) & time_dfs > 0) %>%
  mutate(
    ic_env_4grp = case_when(
      ic_cat == "Low" & env_cat == "Low"  ~ "Low IC / Low Env",
      ic_cat == "Low" & env_cat == "High" ~ "Low IC / High Env",
      ic_cat != "Low" & env_cat == "Low"  ~ "High IC / Low Env",
      TRUE                                 ~ "High IC / High Env"
    ),
    ic_env_4grp = factor(ic_env_4grp, levels = c(
      "High IC / High Env", "High IC / Low Env",
      "Low IC / High Env", "Low IC / Low Env"
    ))
  )

km_fit <- survfit(Surv(time_dfs, event_dfs) ~ ic_env_4grp, data = surv_km)

n_strata <- length(km_fit$strata)
strata_names <- gsub("ic_env_4grp=", "", names(km_fit$strata))
strata_sizes <- km_fit$strata
strata_vec <- rep(strata_names, strata_sizes)

km_df <- tibble(
  time = km_fit$time, estimate = km_fit$surv,
  conf.low = km_fit$lower, conf.high = km_fit$upper,
  strata = strata_vec
)

colors_4grp <- c(
  "High IC / High Env" = "#00468B", "High IC / Low Env" = "#0099B4",
  "Low IC / High Env" = "#ED7D31", "Low IC / Low Env" = "#AD002A"
)

p3A_main <- ggplot(km_df, aes(x = time, y = estimate, color = strata)) +
  geom_step(linewidth = 0.6) +
  scale_color_manual(values = colors_4grp, name = NULL) +
  scale_x_continuous(breaks = seq(0, 16, 2), limits = c(-0.5, 17), expand = c(0, 0)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     limits = c(0.50, 1.00), breaks = seq(0.50, 1.00, 0.10)) +
  labs(x = "Time since baseline (years)", y = "Disability-free survival (%)") +
  theme_lancet +
  theme(
    legend.position = c(0.22, 0.22),
    legend.background = element_rect(fill = alpha("white", 0.9), color = NA),
    legend.key.width = unit(0.8, "cm"), legend.text = element_text(size = 6.5)
  )

risk_times <- seq(0, 16, 2)
risk_summ <- summary(km_fit, times = risk_times)
risk_df <- tibble(
  time = risk_summ$time, n.risk = risk_summ$n.risk,
  strata = gsub("ic_env_4grp=", "", risk_summ$strata)
)

p3A_risk <- ggplot(risk_df, aes(x = time, y = strata,
                                 label = format(n.risk, big.mark = ","))) +
  geom_text(size = 2, family = base_family) +
  scale_x_continuous(breaks = risk_times, limits = c(-0.5, 17), expand = c(0, 0)) +
  scale_y_discrete(limits = rev(names(colors_4grp))) +
  labs(x = NULL, y = NULL) +
  theme_void(base_family = base_family) +
  theme(
    axis.text.y = element_text(size = 5.5, hjust = 1, color = "grey30"),
    plot.margin = margin(0, 10, 2, 8)
  )

p3A <- p3A_main / p3A_risk + plot_layout(heights = c(4, 1))

# --- Panel B: MSM stratified by IC tertile ---
msm_strat <- read_csv("results/msm_stratified.csv", show_col_types = FALSE)
msm_main  <- read_csv("results/msm_main.csv", show_col_types = FALSE) %>%
  filter(analysis == "MSM_main_pooled_strat" & term == "cum_env_prop")

msm_fig <- bind_rows(
  msm_strat %>%
    filter(term == "cum_env_prop") %>%
    select(stratum, estimate, conf.low, conf.high, p.value, n, n_events) %>%
    mutate(label = case_when(
      stratum == "Low_IC"  ~ "Low IC tertile",
      stratum == "Mid_IC"  ~ "Mid IC tertile",
      stratum == "High_IC" ~ "High IC tertile"
    )),
  msm_main %>%
    mutate(label = "Overall (IPTW)", stratum = "Overall",
           n = NA_integer_, n_events = NA_integer_) %>%
    select(stratum, estimate, conf.low, conf.high, p.value, n, n_events, label)
) %>%
  mutate(
    hr_text = sprintf("%.2f (%.2f\u2013%.2f)", estimate, conf.low, conf.high),
    color_val = case_when(
      stratum == "High_IC" ~ lancet_colors["blue"],
      stratum == "Mid_IC"  ~ lancet_colors["ltblue"],
      stratum == "Low_IC"  ~ lancet_colors["red"],
      TRUE                 ~ "grey20"
    )
  )

# Spacer between Overall and tertiles
spacer <- tibble(
  stratum = NA_character_, estimate = NA_real_, conf.low = NA_real_,
  conf.high = NA_real_, p.value = NA_real_, n = NA_integer_,
  n_events = NA_integer_, label = "", hr_text = "", color_val = NA_character_
)

msm_fig_plot <- bind_rows(
  msm_fig %>% filter(stratum == "Overall"),
  spacer,
  msm_fig %>% filter(stratum != "Overall")
)
msm_fig_plot$label <- factor(msm_fig_plot$label,
  levels = rev(c("Overall (IPTW)", "",
                 "High IC tertile", "Mid IC tertile", "Low IC tertile")))

p3B <- ggplot(msm_fig_plot %>% filter(!is.na(estimate)),
              aes(x = estimate, y = label)) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey60", linewidth = 0.4) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, color = color_val),
                 height = 0, linewidth = 0.6) +
  geom_point(aes(color = color_val, fill = color_val),
             shape = 21, size = 3, stroke = 0.8) +
  geom_text(aes(x = max(conf.high, na.rm = TRUE) + 0.03, label = hr_text),
            hjust = 0, size = 2.5, family = base_family) +
  scale_color_identity() + scale_fill_identity() +
  scale_x_continuous(limits = c(0.50, 1.15), breaks = seq(0.5, 1.0, 0.1)) +
  coord_cartesian(clip = "off") +
  labs(x = "Hazard Ratio (95% CI)", y = NULL,
       subtitle = NULL) +
  theme_lancet +
  theme(
    plot.margin = margin(10, 70, 10, 10),
    axis.title = element_text(size = 8)
  )

# --- Build Panel C (Sensitivity forest) before combining ---
cat("  Building Panel C: Sensitivity Analysis Forest...\n")

sens <- read_csv("results/sensitivity_summary.csv", show_col_types = FALSE)

sens_plot <- sens %>%
  filter(!is.na(hr)) %>%
  mutate(
    label = case_when(
      analysis == "S16_main_reference"  ~ "Main analysis (reference)",
      analysis == "S1_ic_sum"           ~ "S1: IC sum score",
      analysis == "S2_env_4indicator"   ~ "S2: Env 4-indicator",
      analysis == "S3_objective_env"    ~ "S3: Objective env proxy (financial + living)",
      analysis == "S4_uncentered_interaction" ~ "S4: Uncentered interaction",
      analysis == "S5_mortality_only"   ~ "S5: Mortality only",
      analysis == "S6_CSH_disability"   ~ "S6: CSH-Disability (death censored)",
      analysis == "S14_CSH_death"       ~ "S14: CSH-Death (disability censored)",
      analysis == "S7_adl_ge2_dfs"      ~ "S7: ADL \u2265 2 threshold",
      analysis == "S8_age_ge65"         ~ "S8: Age \u2265 65",
      analysis == "S9_age_ge70"         ~ "S9: Age \u2265 70",
      analysis == "S10_female_only"     ~ "S10: Female only",
      analysis == "S11_male_only"       ~ "S11: Male only",
      analysis == "S12_adj_education"   ~ "S12: + Education",
      analysis == "S13_adj_marital"     ~ "S13: + Marital status",
      analysis == "S17_ge3_waves"       ~ "S17: \u2265 3 waves only",
      grepl("LOO_excl", analysis)       ~ gsub("S15_LOO_excl_", "S15: Excl. ", analysis),
      TRUE ~ analysis
    ),
    sig = ifelse(p < 0.05, "Significant", "Not significant"),
    is_main = ifelse(analysis == "S16_main_reference", "main", "sensitivity"),
    domain = case_when(
      analysis %in% c("S16_main_reference") ~ "Reference",
      analysis %in% c("S1_ic_sum", "S2_env_4indicator",
                       "S3_objective_env", "S4_uncentered_interaction") ~ "A. Exposure",
      analysis %in% c("S5_mortality_only", "S6_CSH_disability",
                       "S14_CSH_death", "S7_adl_ge2_dfs") ~ "B. Outcome",
      analysis %in% c("S8_age_ge65", "S9_age_ge70",
                       "S10_female_only", "S11_male_only") ~ "C. Population",
      analysis %in% c("S12_adj_education", "S13_adj_marital") |
        grepl("LOO", analysis) ~ "D. Model",
      analysis == "S17_ge3_waves" ~ "E. Bias",
      TRUE ~ "Other"
    )
  )

sens_plot <- sens_plot %>%
  mutate(domain = factor(domain, levels = c(
    "Reference", "A. Exposure", "B. Outcome",
    "C. Population", "D. Model", "E. Bias"
  ))) %>%
  arrange(domain, hr) %>%
  mutate(label = factor(label, levels = rev(label)))

main_hr <- sens_plot$hr[sens_plot$is_main == "main"][1]

p3C <- ggplot(sens_plot, aes(x = hr, y = label)) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey60", linewidth = 0.4) +
  geom_vline(xintercept = main_hr,
             linetype = "dotted", color = lancet_colors["red"], alpha = 0.4) +
  geom_errorbarh(aes(xmin = ci_lo, xmax = ci_hi),
                 height = 0, linewidth = 0.4, color = "grey40") +
  geom_point(aes(fill = sig), shape = 21, size = 2.2, color = "grey30", stroke = 0.5) +
  geom_point(data = . %>% filter(is_main == "main"),
             shape = 23, size = 3, fill = lancet_colors["red"],
             color = lancet_colors["red"]) +
  scale_fill_manual(
    values = c("Significant" = lancet_colors["blue"], "Not significant" = "white"),
    name = NULL
  ) +
  facet_grid(domain ~ ., scales = "free_y", space = "free_y", switch = "y") +
  labs(x = "Hazard Ratio (95% CI) \u2014 IC \u00d7 Environment Interaction", y = NULL) +
  theme_lancet +
  theme(
    strip.text.y.left = element_text(angle = 0, hjust = 1, size = 7, face = "bold"),
    strip.placement   = "outside",
    panel.spacing     = unit(0.3, "cm"),
    legend.position   = c(0.85, 0.05)
  )

# --- Combine Figure 3: (A | B) / C  ---
# Top row: KM curves + MSM stratified; Bottom row: Sensitivity forest (full width)
# wrap_elements prevents patchwork from tagging internal sub-panels (risk table)
top_row <- (wrap_elements(full = p3A) | wrap_elements(full = p3B)) +
  plot_layout(widths = c(1.3, 1))

fig3 <- (top_row / wrap_elements(full = p3C)) +
  plot_layout(heights = c(1, 1.1)) +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(size = 12, face = "bold", family = base_family))

ggsave("figures/fig3_km_msm_sens.pdf", fig3,
       width = fig_width_2col * 2, height = 15, device = cairo_pdf)
ggsave("figures/fig3_km_msm_sens.tiff", fig3,
       width = fig_width_2col * 2, height = 15, dpi = fig_dpi, compression = "lzw")
cat("  Saved fig3_km_msm_sens.pdf/tiff\n")

# Also keep standalone sensitivity forest for eFigure reference if needed
ggsave("figures/fig3C_sensitivity_forest_standalone.pdf", p3C,
       width = fig_width_2col, height = 7, device = cairo_pdf)
cat("  Saved fig3C_sensitivity_forest_standalone.pdf\n")

# ==============================================================================
cat("\n=== Supplementary Figures ===\n")
# ==============================================================================

# --- eFig 1: LCGA trajectories ---
traj_classes <- read_csv("results/lcga_class_trajectories.csv", show_col_types = FALSE)

if (nrow(traj_classes) > 0 && "variable" %in% names(traj_classes)) {
  ic_traj  <- traj_classes %>% filter(variable == "ic_cfa")
  env_traj <- traj_classes %>% filter(variable == "env_formative")

  plot_traj <- function(dat, y_lab) {
    ggplot(dat, aes(x = time, y = mean_y, color = class_label, group = class_label)) +
      geom_line(linewidth = 0.6) +
      geom_ribbon(aes(ymin = mean_y - sd_y / sqrt(pmax(n, 1)),
                      ymax = mean_y + sd_y / sqrt(pmax(n, 1)),
                      fill = class_label),
                  alpha = 0.12, colour = NA) +
      geom_point(size = 1.2) +
      facet_wrap(~ cohort, scales = "free", nrow = 1) +
      scale_color_manual(values = unname(lancet_colors[c("blue", "red", "green", "purple")])) +
      scale_fill_manual(values = unname(lancet_colors[c("blue", "red", "green", "purple")])) +
      labs(x = "Wave", y = y_lab, color = "Trajectory class", fill = "Trajectory class") +
      theme_lancet + theme(legend.position = "bottom")
  }

  if (nrow(ic_traj) > 0) {
    pe1a <- plot_traj(ic_traj, "IC score (CFA)")
    ggsave("figures/efig1a_lcga_ic.pdf", pe1a, width = 14, height = 4, device = cairo_pdf)
    ggsave("figures/efig1a_lcga_ic.tiff", pe1a, width = 14, height = 4,
           dpi = fig_dpi, compression = "lzw")
    cat("  Saved efig1a_lcga_ic.pdf/tiff\n")
  }
  if (nrow(env_traj) > 0) {
    pe1b <- plot_traj(env_traj, "Environment score (formative)")
    ggsave("figures/efig1b_lcga_env.pdf", pe1b, width = 14, height = 4, device = cairo_pdf)
    ggsave("figures/efig1b_lcga_env.tiff", pe1b, width = 14, height = 4,
           dpi = fig_dpi, compression = "lzw")
    cat("  Saved efig1b_lcga_env.pdf/tiff\n")
  }
} else {
  cat("  Trajectory class data not in expected format -- skipping eFig 1\n")
}

# --- eFig 2: IPTW diagnostics ---
wt_diag <- read_csv("results/msm_weights_diagnostics.csv", show_col_types = FALSE)

pe2 <- ggplot(wt_diag, aes(x = cohort, y = wt_mean)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = lancet_colors["red"],
             linewidth = 0.4) +
  geom_point(size = 3, color = lancet_colors["blue"]) +
  geom_errorbar(aes(ymin = wt_mean - wt_sd, ymax = wt_mean + wt_sd),
                width = 0.2, color = lancet_colors["blue"], linewidth = 0.5) +
  geom_text(aes(label = sprintf("%.3f", wt_mean)), vjust = -1.5,
            size = 2.8, family = base_family) +
  scale_y_continuous(limits = c(0.4, 3.2)) +
  labs(x = NULL, y = "Mean stabilized IPTW (\u00b11 SD)") +
  theme_lancet

ggsave("figures/efig2_iptw_diagnostics.pdf", pe2,
       width = fig_width_2col - 2, height = 4, device = cairo_pdf)
ggsave("figures/efig2_iptw_diagnostics.tiff", pe2,
       width = fig_width_2col - 2, height = 4, dpi = fig_dpi, compression = "lzw")
cat("  Saved efig2_iptw_diagnostics.pdf/tiff\n")

# ==============================================================================
cat("\n=== Summary ===\n")
# ==============================================================================

figs <- list.files("figures", pattern = "\\.(pdf|tiff)$")
cat(sprintf("Generated %d figure files:\n", length(figs)))
for (f in sort(figs)) cat(sprintf("  figures/%s\n", f))

cat("\nDisplay item allocation (5 items):\n")
cat("  Fig 1: STROBE flowchart (11_strobe_flowchart.R)\n")
cat("  Fig 2: Panel A (Forest) + Panel B (Marginal effect) + Panel C (5-year risk)\n")
cat("  Fig 3: Panel A (KM + risk table) + Panel B (MSM) + Panel C (Sensitivity)\n")
cat("  Table 1: Baseline characteristics\n")
cat("\nAppendix items:\n")
cat("  eFig 1a/b: LCGA trajectories\n")
cat("  eFig 2: IPTW diagnostics\n")
cat("  eFig 3: Marginal effect standalone (16_marginal_effect_plot.R)\n")
cat("  eTable 1-N: Model estimates, trajectory DFS, sensitivity detail\n")

elapsed <- round(difftime(Sys.time(), t0, units = "mins"), 1)
cat(sprintf("\n=== FIGURES COMPLETE (%.1f min) ===\n", elapsed))
